$ANSIBLE_VAULT;1.1;AES256
36633336613763376263323066636430303561343932326262396564616335326130663334316431
3263666430653334326437326236626630353732353739370a383166303736386263396337336434
35646338336364636537386337636535376266656638306361336636643463633133623331316636
3066333663623333320a393135393532383365316364336162333138326234373931316439303664
33623439343261363932303530343933626365353864306265636465643362326665393533306638
61633339613862653364383737376337323937363432306563633261386166623339623534333365
33373337633466653739313565353039343836653161613461396263363736323831373430363261
63373531383863613735386361303237626134373762353663643666643066313138333639383339
61353139643465303566363062636437373861623965356662643833656162656432333134376133
64313165333732303032383236323134653766323361613561356163326430626333356336336238
326365303830633135303665306662636563
